### ISSUE TITLE
Lines wrongly marked as changed on ISO-8859 files

### ISSUE THREAD

**Issue by lpanebr** [lewis6991/gitsigns.nvim#522]
### Description

Lines with accented characters on ISO-8859 files are wrongly marked as changed:
![image](https://user-images.githubusercontent.com/129185/163250375-64cea1a2-4fa7-49f9-a83e-fb7a2e513289.png)

![image](https://user-images.githubusercontent.com/129185/163250682-64c321b4-0818-4507-8e33-6228b9173fae.png)

Furthermore the whole file is unchanged:
![image](https://user-images.githubusercontent.com/129185/163250769-b9fdd9f6-c025-4d04-a51b-a3af86198690.png)

### Neovim version

NVIM v0.7.0-dev+674-g24f9463dd

### Operating system and version

Ubuntu 20.04.4 LTS

### Expected behavior

Only lines with actual changes should be marked as changed.

### Actual behavior

Lines with accented characters on ISO-8859 files are wrongly marked as changed.

```php
$cfg['dados']['cliente']              = $option->getOption('dados_cliente');

/*****************************************************************
			CONFIGURAÇÕES GERAIS
*****************************************************************/
// Dados do editor do evento
// para uso em assinaturas de email
```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
Sorry, I am not able to reproduce. A minimal config will be needed.

You can try running `:Gitsigns preview_hunk` or `:Gitsigns diffthis` to see what Gitsigns is getting as the index version.

**Comment by lewis6991** [comment]
I'm not really sure. All I know is that `CONFIGURA<c7><d5>ES GERAIS` is what we are getting from `git show :0:<filename>`. I guess the process output needs to be decoded somehow.

**Comment by lpanebr** [comment]
Steps to reproduce:

1. Unzip the file [gitsigns.zip](https://github.com/lewis6991/gitsigns.nvim/files/8490453/gitsigns.zip)
2. Change into the uncompressed `gitsigns` directory
3. Initialize git: `git init && git add . && git commit -m "adding latin1 encoded file"`
4. Open vnim `nvim .`
5. Open the file  `:e latin1.php`

The file will show lines 3 and 8 as changed (2 and 7 in the image below):
![image](https://user-images.githubusercontent.com/129185/163425482-3edaa2bf-8b14-4abe-94c0-8b2c113a1424.png)

**Comment by lewis6991** [comment]
Ok, I've been able to reproduce this by setting `set fileencoding=latin1`. The fix for this will be very difficult as we will need to pass this through something like `iconv`.

If it doesn't impact you too much, I will close this, but it's good to know about these kinds of edge cases.

I'm currently experimenting using `iconv` via `ffi`, but I'm doubtful I'll be able to get it to work.

**Comment by lewis6991** [comment]
@lpanebr I've got a VERY rough PR (#525) to use iconv via FFI. From my usage it appears to "just work".

**Comment by lewis6991** [comment]
@lpanebr , I've cleaned up #525 quite a bit. Are you able to give it a try?

**Comment by lpanebr** [comment]
wow! cool! Unfortunately it still the same problem and the same `:Gitsigns preview_hunk` 😞

**Comment by lewis6991** [comment]
Do you know if your Neovim build has LuaJIT? Your build must also have icov but I'm assuming most builds will have.

**Comment by lewis6991** [comment]
I've updated the PR with some additional debug messages. You can see these with `:Gitsigns debug_messages`. Look for a message with the prefix `doiconv: ...`. If it works, you should see `doiconv: Converting latin1 to utf-8`.

**Comment by lpanebr** [comment]
> Do you know if your Neovim build has LuaJIT?

Not sure how to check that. I know I've built it with the Release build type:
`make CMAKE_BUILD_TYPE=Release`

1. I've enabled debug (I think...) with this
![image](https://user-images.githubusercontent.com/129185/163599912-fa240c26-09c4-4d4a-9e2b-e5fad198baaf.png)
2. Uninstalled and reinstalled the gitsigns extension.
3. Open the my latin1.php file and still no change
![image](https://user-images.githubusercontent.com/129185/163600588-b0154430-5990-41e6-bc27-1d6a4567c9f9.png)
4. When I run `:Gitsigns debug_messages` I get nothing
5. I then try `:messages` but nothing... 🤔

**Comment by lewis6991** [comment]
If `:Gitsigns debug_messages` isn't showing anything, then something is wrong. Maybe you need to run `PackerCompile` or something?

To know if you have luajit just run `nvim --version`.

**Comment by lpanebr** [comment]
Well, **I do have LuaJIT:**
```
NVIM v0.7.0-dev+1453-g8486c87e5
Build type: Release
LuaJIT 2.1.0-beta3
```
Deleted the `packer_compiled.lua` file
![image](https://user-images.githubusercontent.com/129185/163606020-761418d4-2747-4c31-b4f6-ae4f6b0e053d.png)
and recreated it
![image](https://user-images.githubusercontent.com/129185/163606037-eb30aa3d-6f28-4698-a81d-3c89aeb9989a.png)
Same results...


**Now with the `minimal.lua` (no changes in it):**

![image](https://user-images.githubusercontent.com/129185/163606924-04e03bbb-0ab8-4077-bdc4-81a853cfad45.png)

Same results.

But at least now I've got output from `:Gitsigns debug_messages`.
However no `doiconv: Converting latin1 to utf-8` in it:
```
signs.init: Using vimfn signs
run_job: git --no-pager --literal-pathspecs --version
fn: Deriving GitSignsAdd from DiffAdd
fn: Deriving GitSignsChange from DiffChange
fn: Deriving GitSignsDelete from DiffDelete
fn: Deriving GitSignsAddNr from GitSignsAdd
fn: Deriving GitSignsChangeNr from GitSignsChange
fn: Deriving GitSignsDeleteNr from GitSignsDelete
fn: Deriving GitSignsAddLn from DiffAdd
fn: Deriving GitSignsChangeLn from DiffChange
fn: Deriving GitSignsDeleteLn from DiffDelete
fn: Deriving GitSignsCurrentLineBlame from NonText
fn: Deriving GitSignsAddInline from TermCursor
fn: Deriving GitSignsDeleteInline from TermCursor
fn: Deriving GitSignsChangeInline from TermCursor
fn: Deriving GitSignsAddLnInline from GitSignsAddInline
fn: Deriving GitSignsChangeLnInline from GitSignsChangeInline
fn: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
fn: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
fn: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
fn: Deriving GitSignsDeleteVirtLn from GitSignsDeleteLn
fn: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
fn: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
attach(1): Attaching (trigger=BufRead)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir=/home/lpanebr/tmp/gitsigns/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/lpanebr/tmp/gitsigns/latin1.php
watch_gitdir(1): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir=/home/lpanebr/tmp/gitsigns/.git show :0:latin1.php
update(1): updates: 1, jobs: 6
update(1): updates: 2, jobs: 6
update(1): updates: 3, jobs: 6
update(1): updates: 4, jobs: 6
update(1): updates: 5, jobs: 6
update(1): updates: 6, jobs: 6
Press ENTER or type command to continue
```

I also do have `iconv`:
![image](https://user-images.githubusercontent.com/129185/163607425-4186724b-2617-457e-81d2-b57525490e09.png)

**Comment by lewis6991** [comment]
There is no `doconv: ...` message in there. There should be one whether it works or not. Are you sure you have the necessary commit?

**Comment by lpanebr** [comment]
well.. that's embarrassing... I assumed it was on main already.

I'll learn how to install a specific commit and try. SORRY

**Comment by lpanebr** [comment]
With packer I could install the commit with:
```lua
use {
    "lewis6991/gitsigns.nvim",
    commit = "de91d35443d3dfdf744aa144eb978691012d6081"
  }
```

and now I get this errors only when opening my latin1.php file:
![image](https://user-images.githubusercontent.com/129185/163623446-375f74cd-b372-4bae-bc75-e84624a0d0c3.png)

Still don't know how to install a specific commit in the mininal.lua.

**Comment by lewis6991** [comment]
Ok. Looks like your Neovim isn't built with iconv. The error just means this would have failed:

```lua
local iconv_lib = require'ffi'.load'iconv'
```

Can you try running that directly in nvim. I suspect it will error.

**Comment by lpanebr** [comment]
`:lua local iconv_lib = require'ffi'.load'iconv'`
![image](https://user-images.githubusercontent.com/129185/163624771-59e05baf-13ad-4c36-971b-3d1c4d077245.png)


`:local iconv_lib = require'ffi'.load'iconv'`
![image](https://user-images.githubusercontent.com/129185/163624820-08c54903-b3b6-4a42-8b7a-accd4df6d875.png)

**Comment by lewis6991** [comment]
Just found out nvim has a builtin `iconv()` function we can use. No need for this wacky ffi stuff. I've updated the PR. Instead of checking out a commit, just checkout the `iconv` branch.

**Comment by lpanebr** [comment]
IT WORKS!!
🥇 👏👏👏 🤩🤩
@lewis6991 ROCKS!!!

![image](https://user-images.githubusercontent.com/129185/163626126-e9c1bb72-5cbb-402d-a8ea-988e1a8ffd47.png)

**Comment by lewis6991** [comment]
Nice!

Using the builtin makes this so much easier.
